[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "myapp"
version = "0.1.0"
description = "My Python desktop app"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []